---
title: "Model_1"
author: "DCF"
date: "2024-04-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(forecast)
library(lubridate)
```



```{r dataLoad}
getwd()

## Weather Data
weatherData <- read_csv('../Data/Main_Data/Imputed_Combined_Daily_Normals.csv')

## Crop Count Data
cropCountData <- read_csv('../Data/Crop_Data/CaliforniaCropsStationReady.csv')

## Crop Cardinal Data
cropCardinalData <- read_csv('../Data/Crop_Data/CaliforniaCardinalData.csv')


colnames(weatherData)
colnames(cropCountData)
colnames(cropCardinalData)


## Join Crop Data and Cardinal Data
cropInfo <- cropCardinalData %>% 
  inner_join(cropCountData, by = "CropTypes")


## Join Weather Data and Crop Data
#fullData <- cropInfo %>% 
#  inner_join(weatherData, by = "DailyStation")



```


```{r model}
## All of California


## Average daily temperatures across all stations
avgDailyTemps <- weatherData %>%
  group_by(Date) %>%
  summarise(AvgTemp = mean(AvgTemp, na.rm = TRUE))

## Prepare normals data
normals <- weatherData %>%
  group_by(MonthDay) %>%
  summarise(normalAvgTemp = mean(normalAvgTemp, na.rm = TRUE))

## Create historical time series object
start_date <- min(weatherData$Date)
ts_data <- ts(avgDailyTemps$AvgTemp, frequency=365, start=c(year(start_date), month(start_date)))

## Fit a seasonal ARIMA model
model <- auto.arima(ts_data, seasonal=TRUE)
forecasted_values <- forecast(model, h=6*365)  # Forecasting for the next 6 years


#######


## Calculate the end date of the historical data
end_date <- start_date + length(ts_data) - 1

## Generate forecast dates starting the day after the end date
forecast_dates <- seq(end_date + 1, by="day", length.out=6*365)

## Create forecast dataframe for ggplot
forecast_df <- data.frame(
  Date = forecast_dates,
  Temp = forecasted_values$mean,
  Type = "Forecast"
)

## Historical data for ggplot
history_df <- data.frame(
  Date = seq(start_date, by="day", length.out=length(ts_data)),
  Temp = as.vector(ts_data),
  Type = "Historical"
)

## Attach a base year to MonthDay to facilitate plotting (replicating for each year)
normals$Date <- as.Date(paste("2010", normals$MonthDay, sep="-"), format="%Y-%m-%d")
start_year <- min(year(history_df$Date))
end_year <- max(year(forecast_df$Date))

normals_list <- lapply(start_year:end_year, function(y) {
  df <- normals
  df$Date <- as.Date(paste(y, format(df$Date, "%m-%d"), sep="-"), format="%Y-%m-%d")
  return(df)
})
normals_long <- do.call(rbind, normals_list)

normals_long <- normals_long %>%
  select(Date, normalAvgTemp) %>%
  rename(Temp = normalAvgTemp) %>%
  mutate(Type = "Normal")  # Ensure the Type column is added and set to "Normal"


## Combine the data for plotting
plot_data <- rbind(history_df, forecast_df, normals_long)



## Fit Linear Model for Historical Data
lm_historical <- lm(Temp ~ Date, data=history_df)
summary_historical <- summary(lm_historical)

## Fit Linear Model for Forecast Data
lm_forecast <- lm(Temp ~ Date, data=forecast_df)
summary_forecast <- summary(lm_forecast)

## Combine historical and forecast data for linear model fitting
combined_data <- rbind(history_df, forecast_df)

## Fit Linear Model for combined historical and forecast data
lm_combined <- lm(Temp ~ Date, data=combined_data)


## Generate plot with a single LM trend line for combined data
plot <- ggplot(plot_data, aes(x=Date, y=Temp, color=Type)) +
  geom_line(data=filter(plot_data, Type %in% c("Historical", "Forecast")), alpha=.8, size=1) +
  geom_line(data=filter(plot_data, Type == "Normal"), alpha=0.9, size=1.2) +
  geom_abline(slope=coefficients(lm_combined)["Date"], intercept=coefficients(lm_combined)["(Intercept)"], color="darkgreen", size=1.5) +
  scale_color_manual(values=c("Historical"="purple", "Forecast"="orange", "Normal"="black", "LM Trend Combined"="darkgreen")) +
  labs(title="Temperature Forecast and Historical Data with Trend Lines",
       x="Date",
       y="Temperature",
       color="Type") +
  theme_minimal() +
  guides(alpha=FALSE, size=FALSE)

## Print the updated plot
print(plot)

```  


```{r WeatherStationSpecific}

## Filter for specific station
stationData <- weatherData %>% 
  filter(DailyStation == "69015093121")

## Create time series data by metric
ts_list <- stationData %>% 
  select(Date, MaxTemp, MinTemp, AvgTemp) %>%
  pivot_longer(cols = -Date, names_to = "Variable", values_to = "Value") %>%
  group_by(Variable) %>%
  summarise(ts = list(ts(Value, frequency = 365, start = c(year(min(Date)), month(min(Date))))))

#####
# ARIMA Modeling and Forecasting
#####
forecasts <- ts_list %>%
  mutate(
    model = map(ts, auto.arima, seasonal = TRUE),
    forecast = map(model, forecast, h = 365)  # Forecast for next year
  )

#####
# Postprocessing and Plotting
#####

## Prepare data for plotting
forecast_data <- forecasts %>% 
  mutate(
    dates = list(seq(today() + 1, length.out = 365, by = "day")),
    forecast_df = map2(forecast, dates, ~data.frame(Date = .y, Forecast = .x$mean, Variable = .env$Variable))
  ) %>%
  select(Variable, forecast_df) %>%
  unnest(cols = c(forecast_df))

historical_data <- stationData %>%
  select(Date, MaxTemp, MinTemp, AvgTemp) %>%
  pivot_longer(cols = -Date, names_to = "Variable", values_to = "Value") %>%
  mutate(Type = "Historical")

combined_plot_data <- bind_rows(historical_data, forecast_data)

## Generate Plot
ggplot(combined_plot_data, aes(x = Date, y = Value, color = Variable)) +
  geom_line(aes(linetype = Type)) +
  scale_color_manual(values = c("MaxTemp" = "red", "MinTemp" = "blue", "AvgTemp" = 'purple')) +
  labs(title = "Weather Forecast by Metric",
       x = "Date",
       y = "Measurement") +
  theme_minimal()



```  





