---
title: "Index_Analysis"
author: "DCF"
date: "2024-04-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(forecast)
library(lubridate)
library(pbapply)
library(gganimate)
library(viridis)
library(ggmap)
library(leaflet)
library(shiny)
library(shinythemes)
```

## Weather Risk Index

This is a rough draft of the risk index for crops by weather station.  Index values need to be adjusted still.



```{r dataLoad}
getwd()

## Weather Data
weatherData <- read_csv('../Data/Main_Data/Imputed_Combined_Daily_Normals.csv')

## Crop Count Data
cropCountData <- read_csv('../Data/Crop_Data/CaliforniaCropsStationReady.csv')

## Crop Cardinal Data
cropCardinalData <- read_csv('../Data/Crop_Data/CaliforniaCardinalData.csv')

## Colnames Check
colnames(weatherData)
colnames(cropCountData)
colnames(cropCardinalData)

## Convert temperatures from Celsius to Fahrenheit in cropCardinalData
cropCardinalData <- cropCardinalData %>%
  mutate(
    OptimalTempMin_F = OptimalTempMin_C * 9/5 + 32,
    OptimalTempMax_F = OptimalTempMax_C * 9/5 + 32,
    AbsTempMin_F = AbsTempMin_C * 9/5 + 32,
    AbsTempMax_F = AbsTempMax_C * 9/5 + 32
  )

## Join Crop Cardinal Data with Crop Count Data
cropInfo <- cropCardinalData %>%
  inner_join(cropCountData, by = "CropTypes") %>%
  select(-c(OptimalTempMin_C, OptimalTempMax_C, AbsTempMin_C, AbsTempMax_C)) # Remove Celsius columns


```   


## Daily Risk Index
```{r dailyRiskIndex}

############################
### Daily Risk Index
############################

## Add month and year columns to the weather data for easier grouping
weatherData <- weatherData %>%
  mutate(
    Month = month(Date),
    Year = year(Date)
  )

############################
### Risk Assessment Function
############################
calculateRisk <- function(avgTemp, minTemp, maxTemp, optMin, optMax, absMin, absMax, heatVulnerability, frostVulnerability) {
  riskLevels <- c(
    avg = ifelse(avgTemp < optMin || avgTemp > optMax, 1, 0),
    min = ifelse(minTemp < absMin, ifelse(frostVulnerability == "Critical", 3, 2), 0),
    max = ifelse(maxTemp > absMax, ifelse(heatVulnerability == "Critical", 3, 2), 0)
  )
  
  ## Calculate cumulative risk score for the day
  totalRisk <- sum(riskLevels)
  
  ############################
  ### Risk Category Score
  ############################
  if (totalRisk >= 5) {
    return("Critical Above")
  } else if (totalRisk >= 4 && riskLevels['max'] >= 2) {
    return("Critical Above")
  } else if (totalRisk >= 4 && riskLevels['min'] >= 2) {
    return("Critical Below")
  } else if (totalRisk >= 2) {
    return("Severe")
  } else if (totalRisk > 0) {
    return("Moderate")
  } else {
    return("None")
  }
}


## Process each crop type, station, and apply daily calculations
results <- pblapply(unique(cropInfo$CropTypes), function(crop) {
  cropData <- cropInfo[cropInfo$CropTypes == crop,]
  
  stationResults <- lapply(unique(cropData$DailyStation), function(station) {
    stationWeather <- weatherData[weatherData$DailyStation == station,]
    
    ## Filter crop data to match each station's date range exactly
    specificCropData <- cropData[cropData$DailyStation == station, ]

    ############################
    ### Perform Risk Assessments
    ############################
    dailyRisks <- data.frame(
      Station = rep(station, nrow(stationWeather)),
      Crop = rep(crop, nrow(stationWeather)),
      Month = stationWeather$Month,
      Year = stationWeather$Year,
      Risk = mapply(calculateRisk, 
                    avgTemp = stationWeather$AvgTemp, 
                    minTemp = stationWeather$MinTemp, 
                    maxTemp = stationWeather$MaxTemp, 
                    optMin = specificCropData$OptimalTempMin_F[1], 
                    optMax = specificCropData$OptimalTempMax_F[1], 
                    absMin = specificCropData$AbsTempMin_F[1], 
                    absMax = specificCropData$AbsTempMax_F[1],
                    heatVulnerability = specificCropData$HeatVulnerability[1], 
                    frostVulnerability = specificCropData$FrostVulnerability[1]),
      DaysOptimal = as.integer(stationWeather$AvgTemp >= specificCropData$OptimalTempMin_F[1] & stationWeather$AvgTemp <= specificCropData$OptimalTempMax_F[1]),
      DaysAbsolute = as.integer(stationWeather$MinTemp >= specificCropData$AbsTempMin_F[1] & stationWeather$MaxTemp <= specificCropData$AbsTempMax_F[1])
    )

    ############################
    ### Risk Column Names : Group by month and year, then summarize
    ############################
    monthlySummary <- dailyRisks %>%
      group_by(Station, Crop, Month, Year) %>%
      summarise(
        DaysOptimal = sum(DaysOptimal),
        DaysAbsolute = sum(DaysAbsolute),
        CriticalAbove = sum(Risk == "Critical Above"),
        CriticalBelow = sum(Risk == "Critical Below"),
        Severe = sum(Risk == "Severe"),
        Moderate = sum(Risk == "Moderate"),
        TotalDays = n(),
        .groups = 'drop'
      )
    
    return(monthlySummary)
  })
  
  ## Combine station results for this crop
  do.call(rbind, stationResults)
})


## Combine all results
dailyResults <- do.call(rbind, results)


## Print final results to review
print(dailyResults)



## Rename 'Station' to 'DailyStation' for consistency
dailyResults <- dailyResults %>%
  rename(DailyStation = Station)



## Oranges Check
myOranges <- dailyResults %>% 
  filter(Crop == "Oranges")
  

```   



```{r viz}

##### Visualizations #####

### ROUGH netRiskScore ###

## Ideas: 
## - Have Hot/Cold separation with color 
## - 
##

## Calculate a Net Risk Score
dailyResults <- dailyResults %>%
  mutate(NetRiskScore = 
           (DaysOptimal - (CriticalAbove + CriticalBelow + Severe * 0.5 + Moderate * 0.25)) / TotalDays)

### These weights will need to be adjusted

## Get Lat/Long from DailyStation Mapping from weatherData
stationMetadata <- weatherData %>%
  select(DailyStation, DailyLat, DailyLong) %>%
  distinct()

### ::TODO:: Add County Name for Info on SHINY App



## Merge Lat/Long to Index
dailyResults <- dailyResults %>%
  left_join(stationMetadata, by = "DailyStation")


dailyResults <- dailyResults %>%
  mutate(
    Year = as.numeric(Year),
    Month = as.numeric(Month),
    Date = paste(Year, Month, "1", sep = "-"),  ## Create a 'Date' column for animation
    Date = as.Date(Date, format = "%Y-%m-%d")   ## Convert to Date object
  )


# ## Leaflet Test Plot
# leaflet(data = dailyResults) %>% 
#   addTiles() %>%  ## Add default OpenStreetMap map tiles
#   addCircles(lng = ~DailyLong, lat = ~DailyLat, weight = 1,
#              radius = ~NetRiskScore * 1000,  # Adjust radius based on your data scale
#              color = ~colorNumeric("viridis", NetRiskScore)(NetRiskScore)) %>%
#   addLegend("bottomright", pal = colorNumeric("viridis", dailyResults$NetRiskScore), 
#             values = ~NetRiskScore, title = "Net Risk Score")


```  


## Normal Index
```{r normalIndex}
############################
### Normal Risk Index
############################



############################
### Risk Assessment Function
############################
calculateRisk <- function(avgTemp, minTemp, maxTemp, optMin, optMax, absMin, absMax, heatVulnerability, frostVulnerability) {
  riskLevels <- c(
    avg = ifelse(avgTemp < optMin || avgTemp > optMax, 1, 0),
    min = ifelse(minTemp < absMin, ifelse(frostVulnerability == "Critical", 3, 2), 0),
    max = ifelse(maxTemp > absMax, ifelse(heatVulnerability == "Critical", 3, 2), 0)
  )
  
  ## Calculate cumulative risk score for the day
  totalRisk <- sum(riskLevels)
  
  ############################
  ### Risk Category Score
  ############################
  if (totalRisk >= 5) {
    return("Critical Above")
  } else if (totalRisk >= 4 && riskLevels['max'] >= 2) {
    return("Critical Above")
  } else if (totalRisk >= 4 && riskLevels['min'] >= 2) {
    return("Critical Below")
  } else if (totalRisk >= 2) {
    return("Severe")
  } else if (totalRisk > 0) {
    return("Moderate")
  } else {
    return("None")
  }
}


## Process each crop type, station, and apply daily calculations
results <- pblapply(unique(cropInfo$CropTypes), function(crop) {
  cropData <- cropInfo[cropInfo$CropTypes == crop,]
  
  stationResults <- lapply(unique(cropData$DailyStation), function(station) {
    stationWeather <- weatherData[weatherData$DailyStation == station,]
    
    ## Filter crop data to match each station's date range exactly
    specificCropData <- cropData[cropData$DailyStation == station, ]

    ############################
    ### Perform Risk Assessments
    ############################
    dailyRisks <- data.frame(
      Station = rep(station, nrow(stationWeather)),
      Crop = rep(crop, nrow(stationWeather)),
      Month = stationWeather$Month,
      Year = stationWeather$Year,
      Risk = mapply(calculateRisk, 
                    avgTemp = stationWeather$normalAvgTemp, 
                    minTemp = stationWeather$normalMinTemp, 
                    maxTemp = stationWeather$normalMaxTemp, 
                    optMin = specificCropData$OptimalTempMin_F[1], 
                    optMax = specificCropData$OptimalTempMax_F[1], 
                    absMin = specificCropData$AbsTempMin_F[1], 
                    absMax = specificCropData$AbsTempMax_F[1],
                    heatVulnerability = specificCropData$HeatVulnerability[1], 
                    frostVulnerability = specificCropData$FrostVulnerability[1]),
      DaysOptimal = as.integer(stationWeather$normalAvgTemp >= specificCropData$OptimalTempMin_F[1] & stationWeather$normalAvgTemp <= specificCropData$OptimalTempMax_F[1]),
      DaysAbsolute = as.integer(stationWeather$normalMinTemp >= specificCropData$AbsTempMin_F[1] & stationWeather$normalMaxTemp <= specificCropData$AbsTempMax_F[1])
    )    
    
    
    ############################
    ### Risk Column Names : Group by month and year, then summarize
    ############################
    monthlySummary <- dailyRisks %>%
      group_by(Station, Crop, Month, Year) %>%
      summarise(
        DaysOptimal = sum(DaysOptimal),
        DaysAbsolute = sum(DaysAbsolute),
        CriticalAbove = sum(Risk == "Critical Above"),
        CriticalBelow = sum(Risk == "Critical Below"),
        Severe = sum(Risk == "Severe"),
        Moderate = sum(Risk == "Moderate"),
        TotalDays = n(),
        .groups = 'drop'
      )
    
    return(monthlySummary)
  })
  
  ## Combine station results for this crop
  do.call(rbind, stationResults)
})



## Combine all results
normalResults <- do.call(rbind, results)

## Print final results to review
print(normalResults)


## Rename 'Station' to 'DailyStation' for consistency
normalResults <- normalResults %>%
  rename(DailyStation = Station)


```   


```{r calculateIndex and Plot}
############################
### Calculate Index and Plot
############################

calculateAndVisualizeRisk <- function(data, weatherData) {

  ## Calculate a Net Risk Score
  dailyResults <- data %>%
    mutate(NetRiskScore = 
           (DaysOptimal - (CriticalAbove + CriticalBelow + Severe * 0.5 + Moderate * 0.25)) / TotalDays)
  
  ## !!!THESE WEIGHTS NEED FURTHER ADJUSTMENT!!!

  ## Get Lat/Long from DailyStation Mapping from weatherData
  stationMetadata <- weatherData %>%
    select(DailyStation, DailyLat, DailyLong) %>%
    distinct()

  ## ::TODO:: Add County Name for Info on SHINY App

  ## Merge Lat/Long to Index
  dailyResults <- dailyResults %>%
    left_join(stationMetadata, by = "DailyStation") %>%
    mutate(
      Year = as.numeric(Year),
      Month = as.numeric(Month),
      Date = as.Date(paste(Year, Month, "1", sep = "-"), format = "%Y-%m-%d")  ## Convert to Date object for use in animation or time series
    )

  ## Print final results to review
  print(dailyResults)

  # ## Leaflet Map Visualization
  # map <- leaflet(data = dailyResults) %>% 
  #   addTiles() %>%  ## Add default OpenStreetMap map tiles
  #   addCircles(lng = ~DailyLong, lat = ~DailyLat, weight = 1,
  #              radius = ~NetRiskScore * 1000,  # Adjust radius based on your data scale
  #              color = ~colorNumeric("viridis", NetRiskScore)(NetRiskScore)) %>%
  #   addLegend("bottomright", pal = colorNumeric("viridis", dailyResults$NetRiskScore), 
  #             values = ~NetRiskScore, title = "Net Risk Score")
  # 
  # ## Output the map for visualization
  # print(map)
  
  ## Return final processed DataFrame (optional)
  return(dailyResults)
}

## Calculate Results
normalResults <- calculateAndVisualizeRisk(normalResults, weatherData)


```  


## Write to CSV
```{r write csvs}
#### CSV Write/Export

## Write Daily Index Dataframe to CSV
write.csv(dailyResults, 'indexRoughDraftDaily.csv', row.names = FALSE)

## Write Normal Index Dataframe to CSV
write.csv(normalResults, 'indexRoughDraftNormal.csv', row.names = FALSE)

```  




```{r shiny}


#### R Shiny Risk Index Dashboard ####

### ::TODO:: Add County Name for Info on SHINY App
### ::TODO:: Add Info on Click for County and Station Name
### ::TODO:: Have continuous scale (Daily)

## Define UI for the application
ui <- fluidPage(
  theme = shinytheme("flatly"),  # Using shinythemes for better aesthetics
  titlePanel("Dynamic Risk Mapping by Crop Type and Date"),
  sidebarLayout(
    sidebarPanel(
      selectInput("selectedCrop", "Choose a Crop:", choices = unique(dailyResults$Crop)),
      sliderInput("selectedYear", "Year:", min = min(dailyResults$Year), max = max(dailyResults$Year), value = min(dailyResults$Year)),
      sliderInput("selectedMonth", "Month:", min = 1, max = 12, value = 1),
      tags$hr(),
      tags$p("Adjust the filters to change the maps dynamically. The risk levels are visualized by color intensity, with more severe risks shown in more intense colors."),
      tags$p("Maps provide a visual representation of daily and historical normal risk indices for selected crops, highlighting areas of critical concern.")
    ),
    mainPanel(
      h4("Daily Risk Index Map"),
      leafletOutput("dailyMap"),
      h4("Normal Risk Index Map"),
      leafletOutput("normalMap")
    )
  )
)

server <- function(input, output) {
  # Compute common color scale domain
  observe({
    combinedData <- bind_rows(
      dailyResults %>% filter(Crop == input$selectedCrop),
      normalResults %>% filter(Crop == input$selectedCrop)
    )
    update <- reactive({ range(combinedData$NetRiskScore, na.rm = TRUE) })
    colorPalette <- colorNumeric(palette = c("red", "green"), domain = update())
    
    output$dailyMap <- renderLeaflet({
      filteredDaily <- dailyResults %>%
        filter(Crop == input$selectedCrop, Year == input$selectedYear, Month == input$selectedMonth)
    
      leaflet(data = filteredDaily) %>%
        addProviderTiles(providers$CartoDB.Positron) %>%
        addCircles(
          lng = ~DailyLong, lat = ~DailyLat, weight = 1,
          radius = ~ifelse(NetRiskScore < 0, -NetRiskScore * 1500, NetRiskScore * 1000),
          color = ~colorPalette(NetRiskScore),
          opacity = 1, fillOpacity = 0.8,
          popup = ~paste("<strong>", Crop, "</strong><br/>",
                         "Risk Score: ", NetRiskScore,
                         "<br/>Station: ", DailyStation)
        ) %>%
        addLegend("bottomright", pal = colorPalette, values = ~NetRiskScore, title = "Net Risk Score")
    })    
    
    

    output$normalMap <- renderLeaflet({
      filteredNormal <- normalResults %>%
        filter(Crop == input$selectedCrop, Year == input$selectedYear, Month == input$selectedMonth)

      leaflet(data = filteredNormal) %>%
        addProviderTiles(providers$CartoDB.Positron) %>%
        addCircles(
          lng = ~DailyLong, lat = ~DailyLat, weight = 1,
          radius = ~ifelse(NetRiskScore < 0, -NetRiskScore * 1500, NetRiskScore * 1000),
          color = ~colorPalette(NetRiskScore),
          opacity = 1, fillOpacity = 0.8,
          popup = ~paste("<strong>", Crop, "</strong><br/>",
                         "Risk Score: ", NetRiskScore,
                         "<br/>Station: ", DailyStation)
        ) %>%
        addLegend("bottomright", pal = colorPalette, values = ~NetRiskScore, title = "Net Risk Score")
    })
  })
}

## Run the application
shinyApp(ui = ui, server = server)



```  









