---
title: "Index_V3"
author: "DCF"
date: "2024-04-21"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(forecast)
library(lubridate)
library(pbapply)
library(gganimate)
library(viridis)
library(ggmap)
library(leaflet)
library(shiny)
library(shinythemes)
library(ggpubr)
```



## Index V3
```{r dataLoad, echo = FALSE, message = FALSE}
## Weather Data
weatherData <- read_csv('../Data/Main_Data/Imputed_Combined_Daily_Normals.csv')

## Crop Count Data
cropCountData <- read_csv('../Data/Crop_Data/CaliforniaCropsStationReady.csv')

## Crop Cardinal Data
cropCardinalData <- read_csv('../Data/Crop_Data/CaliforniaCardinalData.csv')


## Convert temperatures from Celsius to Fahrenheit in cropCardinalData
cropCardinalData <- cropCardinalData %>%
  mutate(
    OptimalTempMin_F = OptimalTempMin_C * 9/5 + 32,
    OptimalTempMax_F = OptimalTempMax_C * 9/5 + 32,
    AbsTempMin_F = AbsTempMin_C * 9/5 + 32,
    AbsTempMax_F = AbsTempMax_C * 9/5 + 32
  )

## Join Crop Cardinal Data with Crop Count Data
cropInfo <- cropCardinalData %>%
  inner_join(cropCountData, by = "CropTypes") %>%
  select(-c(OptimalTempMin_C, OptimalTempMax_C, AbsTempMin_C, AbsTempMax_C)) # Remove Celsius columns



```  


## Statistical Threshold  
```{r statisticalThreshold, message = FALSE}

############################
### Statistical Threshold: Binary
############################

## Add month and year columns to the weather data for easier grouping
weatherData <- weatherData %>%
  mutate(
    Month = month(Date),
    Year = year(Date),
    HighThresholdAvg = normalAvgTemp + 2 * normalAvgTempStd,
    LowThresholdAvg = normalAvgTemp - 2 * normalAvgTempStd,
    HighThresholdMax = normalMaxTemp + 2 * normalMaxTempStd,
    LowThresholdMax = normalMaxTemp - 2 * normalMaxTempStd,
    HighThresholdMin = normalMinTemp + 2 * normalMinTempStd,
    LowThresholdMin = normalMinTemp - 2 * normalMinTempStd
  )

## Process each crop type and station, applying daily calculations
dailyResults <- lapply(unique(cropInfo$CropTypes), function(crop) {
  cropData <- cropInfo[cropInfo$CropTypes == crop,]
  stationResults <- lapply(unique(cropData$DailyStation), function(station) {
    stationWeather <- weatherData[weatherData$DailyStation == station,]
    specificCropData <- cropData[cropData$DailyStation == station, ]


## Daily tracking of temperature conditions incorporating all checks
dailyTemps <- stationWeather %>%
  mutate(
    Station = station,
    Crop = crop,
    DailyCounty = DailyCounty,
    DailyLat = DailyLat,
    DailyLong = DailyLong,
    Fog = Fog,
    Rain_Drizzle = Rain_Drizzle,     ## Indicator for Rain/Drizzle occurrence
    Snow_Ice = Snow_Ice,             ## Indicator for Snow/Ice occurrence
    Hail = Hail,                     ## Indicator for Hail occurrence
    Thunder = Thunder,               ## Indicator for Thunder occurrence
    Tornado_Funnel = Tornado_Funnel, ## Indicator for Tornado/Funnel occurrence
    Precipitation = Precipitation,   ## Total Precipitation amount
    
    ## Cardinal temperature checks for average temperatures
    DaysAvgTempOptimal = as.integer(AvgTemp >= specificCropData$OptimalTempMin_F[1] &         ## Days Avg Temp Within Optimal Range
                                      AvgTemp <= specificCropData$OptimalTempMax_F[1]),
    DaysAvgTempAbs = as.integer(AvgTemp >= specificCropData$AbsTempMin_F[1] &                 ## Days Avg Temp Within Absolute Range
                                  AvgTemp <= specificCropData$AbsTempMax_F[1]),
    DaysAvgTempAboveOptMax = as.integer(AvgTemp > specificCropData$OptimalTempMax_F[1]),      ## Days Avg Temp Above Optimal Max
    DaysAvgTempBelowOptMin = as.integer(AvgTemp < specificCropData$OptimalTempMin_F[1]),      ## Days Avg Temp Below Optimal Min
    DaysAvgTempAboveAbsMax = as.integer(AvgTemp > specificCropData$AbsTempMax_F[1]),          ## Days Avg Temp Above Absolute Max
    DaysAvgTempBelowAbsMin = as.integer(AvgTemp < specificCropData$AbsTempMin_F[1]),          ## Days Avg Temp Below Absolute Min
    
    ## Cardinal temperature checks for minimum temperatures
    DaysMinTempOptimal = as.integer(MinTemp >= specificCropData$OptimalTempMin_F[1] &         ## Days Min Temp Within Optimal Range
                                     MinTemp <= specificCropData$OptimalTempMax_F[1]),
    DaysMinTempAbs = as.integer(MinTemp >= specificCropData$AbsTempMin_F[1] &                 ## Days Min Temp Within Absolute Range
                                  MinTemp <= specificCropData$AbsTempMax_F[1]),
    DaysMinTempAboveOptMax = as.integer(MinTemp > specificCropData$OptimalTempMax_F[1]),      ## Days Min Temp Above Optimal Max
    DaysMinTempBelowOptMin = as.integer(MinTemp < specificCropData$OptimalTempMin_F[1]),      ## Days Min Temp Below Optimal Min
    
    ## Cardinal temperature checks for maximum temperatures
    DaysMaxTempOptimal = as.integer(MaxTemp >= specificCropData$OptimalTempMin_F[1] &         ## Days Max Temp Within Optimal Range
                                     MaxTemp <= specificCropData$OptimalTempMax_F[1]),
    DaysMaxTempAbs = as.integer(MaxTemp >= specificCropData$AbsTempMin_F[1] &                 ## Days Max Temp Within Absolute Range
                                 MaxTemp <= specificCropData$AbsTempMax_F[1]),
    DaysMaxTempAboveOptMax = as.integer(MaxTemp > specificCropData$OptimalTempMax_F[1]),      ## Days Max Temp Above Optimal Max
    DaysMaxTempBelowOptMin = as.integer(MaxTemp < specificCropData$OptimalTempMin_F[1]),      ## Days Max Temp Below Optimal Min
    
    ## Extreme conditions
    ExtremeMinAboveOptMax = as.integer(MinTemp > specificCropData$OptimalTempMax_F[1]),       ## Min Temp Above Optimal Max (Extreme Condition)
    ExtremeMaxBelowOptMin = as.integer(MaxTemp < specificCropData$OptimalTempMin_F[1]),       ## Max Temp Below Optimal Min (Extreme Condition)
    ExtremeMinAboveAbsMax = as.integer(MinTemp > specificCropData$AbsTempMax_F[1]),           ## Min Temp Above Absolute Max (More Extreme Condition)
    ExtremeMaxBelowAbsMin = as.integer(MaxTemp < specificCropData$AbsTempMin_F[1]),           ## Max Temp Below Absolute Min (More Extreme Condition)
    
    ## Deviation checks against the 30-year normals
    AvgTempAboveNorm = AvgTemp > HighThresholdAvg,                                         ## Days Avg Temp Above 30-Year Avg High Threshold
    AvgTempBelowNorm = AvgTemp < LowThresholdAvg,                                          ## Days Avg Temp Below 30-Year Avg Low Threshold
    MinTempAboveNorm = MinTemp > HighThresholdMin,                                         ## Days Min Temp Above 30-Year Min High Threshold
    MinTempBelowNorm = MinTemp < LowThresholdMin,                                          ## Days Min Temp Below 30-Year Min Low Threshold
    MaxTempAboveNorm = MaxTemp > HighThresholdMax,                                         ## Days Max Temp Above 30-Year Max High Threshold
    MaxTempBelowNorm = MaxTemp < LowThresholdMax                                           ## Days Max Temp Below 30-Year Max Low Threshold
  ) %>%
  group_by(Station, Crop, Month, Year, DailyCounty, DailyLat, DailyLong) %>%
  summarise(
    TotalPrecipitation = sum(Precipitation, na.rm = TRUE),                                 ## Summing up total precipitation for the group
    TotalDays = n(),                                                                       ## Counting total days considered in the group
    across(starts_with("Days"), sum),                                                      ## Summing up all days indicators across conditions
    across(ends_with("Norm"), sum),                                                        ## Summing up all days indicators for norms
    across(starts_with("Extreme"), sum),
    .groups = 'drop'
  )

return(dailyTemps)    
  })

  ## Combine station results for this crop
  do.call(rbind, stationResults)
})

## Combine all results
finalResults <- do.call(rbind, dailyResults)


## Rename 'Station' to 'DailyStation' for consistency
finalResults <- finalResults %>%
  rename(DailyStation = Station) %>% 
  select(-STATE_CODE_norm)

## Write the dataframe to a CSV file
write_csv(finalResults, "../Data/Statistical_Threshold_Output.csv")
```   


```{r indexEDA, echo = FALSE, out.width= '50%'}

############################
### Statistical Threshold: Binary Visualizations
############################

# Define the variables you want to plot
variables_to_plot <- c("DaysAvgTempOptimal", "DaysAvgTempAbs", "DaysAvgTempAboveOptMax", "DaysAvgTempBelowOptMin",
                       "DaysAvgTempAboveAbsMax", "DaysAvgTempBelowAbsMin", "DaysMinTempOptimal", "DaysMinTempAbs",
                       "DaysMinTempAboveOptMax", "DaysMinTempBelowOptMin", "DaysMaxTempOptimal", "DaysMaxTempAbs",
                       "DaysMaxTempAboveOptMax", "DaysMaxTempBelowOptMin", "AvgTempAboveNorm", "AvgTempBelowNorm",
                       "MinTempAboveNorm", "MinTempBelowNorm", "MaxTempAboveNorm", "MaxTempBelowNorm")


## Find the first station for Example
first_station <- unique(finalResults$DailyStation)[1]

## Filter data for the first station and create the Date column
station_data <- finalResults %>%
  filter(DailyStation == first_station) %>%
  mutate(Date = as.Date(paste(Year, Month, "1", sep = "-")))

## Generate plots
plots <- list()
for (var in variables_to_plot) {
  plot <- ggplot(station_data, aes(x = Date, y = !!sym(var), group = Crop, color = Crop)) +
    geom_line() +
    facet_wrap(~ Crop, scales = "free_y") +
    labs(x = "Year-Month", y = var, title = paste("Seasonal Progression of", var, "at Station", first_station)) +
    scale_color_viridis_d(end = 0.9) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none")
  
  plots[[var]] <- plot  ## Store each plot in the list
}

## Output plots one by one
for (i in seq_along(plots)) {
  print(plots[[i]])
}

```  


```{r threshold2}
############################
### Statistical Threshold: Deviations
############################

## Set 30 Year Normal Thresholds with their Standard Deviations
weatherData <- weatherData %>%
  mutate(
    Month = month(Date),
    Year = year(Date),
    HighThresholdAvg = normalAvgTemp + 2 * normalAvgTempStd,
    LowThresholdAvg = normalAvgTemp - 2 * normalAvgTempStd,
    HighThresholdMax = normalMaxTemp + 2 * normalMaxTempStd,
    LowThresholdMax = normalMaxTemp - 2 * normalMaxTempStd,
    HighThresholdMin = normalMinTemp + 2 * normalMinTempStd,
    LowThresholdMin = normalMinTemp - 2 * normalMinTempStd
  )

############################
### Process data for each crop type and station, calculating temperature deviations
############################
dailyResults <- lapply(unique(cropInfo$CropTypes), function(crop) {
  cropData <- cropInfo[cropInfo$CropTypes == crop,]
  stationResults <- lapply(unique(cropData$DailyStation), function(station) {
    stationWeather <- weatherData[weatherData$DailyStation == station,]
    specificCropData <- cropData[cropData$DailyStation == station, ]

    ## Daily tracking of temperature conditions incorporating deviation magnitude checks with detailed comments
    dailyTemps <- stationWeather %>%
      mutate(
        
        ## Select Columns to Keep from Station Weather
        Station = station,
        Crop = crop,
        DailyCounty = DailyCounty,   ## Include county information for localized analysis
        DailyLat = DailyLat,
        DailyLong = DailyLong,
        
        ## Calculate deviation magnitudes from optimal and absolute temperature thresholds
        DeviationAvgBelowOptMin = pmax(0, specificCropData$OptimalTempMin_F[1] - AvgTemp),  ## Deviation when AvgTemp is below optimal minimum
        DeviationAvgAboveOptMax = pmax(0, AvgTemp - specificCropData$OptimalTempMax_F[1]),  ## Deviation when AvgTemp is above optimal maximum
        DeviationAvgBelowAbsMin = pmax(0, specificCropData$AbsTempMin_F[1] - AvgTemp),      ## Deviation when AvgTemp is below absolute minimum
        DeviationAvgAboveAbsMax = pmax(0, AvgTemp - specificCropData$AbsTempMax_F[1]),      ## Deviation when AvgTemp is above absolute maximum
        DeviationMinBelowOptMin = pmax(0, specificCropData$OptimalTempMin_F[1] - MinTemp),  ## Deviation when MinTemp is below optimal minimum
        DeviationMaxAboveOptMax = pmax(0, MaxTemp - specificCropData$OptimalTempMax_F[1]),  ## Deviation when MaxTemp is above optimal maximum
        DeviationMinBelowAbsMin = pmax(0, specificCropData$AbsTempMin_F[1] - MinTemp),      ## Deviation when MinTemp is below absolute minimum
        DeviationMaxAboveAbsMax = pmax(0, MaxTemp - specificCropData$AbsTempMax_F[1]),      ## Deviation when MaxTemp is above absolute maximum
        
        ## Calculate deviations from 30-year normals
        DeviationAvgBelowNorm = pmax(0, LowThresholdAvg - AvgTemp),                         ## Deviation when AvgTemp is below 30-year normal low
        DeviationAvgAboveNorm = pmax(0, AvgTemp - HighThresholdAvg),                        ## Deviation when AvgTemp is above 30-year normal high
        DeviationMinBelowNorm = pmax(0, LowThresholdMin - MinTemp),                         ## Deviation when MinTemp is below 30-year normal low
        DeviationMaxAboveNorm = pmax(0, MaxTemp - HighThresholdMax)                         ## Deviation when MaxTemp is above 30-year normal high
      ) %>%
      group_by(Station, Crop, Month, Year, DailyCounty, DailyLat, DailyLong) %>%
      summarise(
        ## Total up Deviations
        TotalDeviationColdOpt = sum(DeviationAvgBelowOptMin, DeviationMinBelowOptMin, na.rm = TRUE),
        TotalDeviationHeatOpt = sum(DeviationAvgAboveOptMax, DeviationMaxAboveOptMax, na.rm = TRUE),
        TotalDeviationColdAbs = sum(DeviationAvgBelowAbsMin, DeviationMinBelowAbsMin, na.rm = TRUE),
        TotalDeviationHeatAbs = sum(DeviationAvgAboveAbsMax, DeviationMaxAboveAbsMax, na.rm = TRUE),
        TotalNormDeviationCold = sum(DeviationAvgBelowNorm, DeviationMinBelowNorm, na.rm = TRUE),    ## Sum of all cold deviations from normal
        TotalNormDeviationHot = sum(DeviationAvgAboveNorm, DeviationMaxAboveNorm, na.rm = TRUE),     ## Sum of all hot deviations from normal
        TotalNormDeviation = sum(DeviationAvgBelowNorm, DeviationAvgAboveNorm, DeviationMinBelowNorm, DeviationMaxAboveNorm, na.rm = TRUE),
        TotalDays = n(),
        .groups = 'drop'
      )

    return(dailyTemps)
  })

  ## Combine station results for each crop
  do.call(rbind, stationResults)
})

############################
### Clean Deviations Output
############################

## Get Crop Count to Merge into Results
cropInfoSubset <- unique(cropInfo[, c("Year", "CropTypes", "DailyStation", "Count")])

## Combine all results across crops
finalResults <- do.call(rbind, dailyResults)

## Convert scientific notation to standard notation for numeric fields
finalResults <- finalResults %>%
  mutate(across(where(is.numeric), ~format(., scientific = FALSE)))


## Rename 'Station' to 'DailyStation' for consistency and remove any unwanted columns
finalResults <- finalResults %>%
  rename(DailyStation = Station)

## Rename column in cropInfoSubset to match finalResults
names(cropInfoSubset)[names(cropInfoSubset) == "CropTypes"] <- "Crop"

## Merge `finalResults` with `cropInfoSubset` using a left join
finalResults <- merge(finalResults, cropInfoSubset, 
                      by = c("Year", "Crop", "DailyStation"), 
                      all.x = TRUE)

## Replace NA in 'Count' column with 0
finalResults <- finalResults %>%
  mutate(Count = replace_na(Count, 0))


## Review final results
print(finalResults)


myOranges <- finalResults %>% 
  filter(Crop == 'Oranges') %>% 
  filter(DailyCounty == 'Fresno')

head(myOranges, 1)
```   


```{r Index}

############################
### Risk Index: Dynamic
############################

## Create a lookup table with numerical weights for vulnerabilities
vulnerability_weights <- cropInfo %>%
  select(CropTypes, FrostVulnerability, HeatVulnerability) %>%
  distinct() %>%
  mutate(
    
    ## Frost Vulnerabilitiy Weights
    FrostVulnerabilityWeight = case_when(
      FrostVulnerability == "Critical" ~ 5,
      FrostVulnerability == "High" ~ 3,
      FrostVulnerability == "Moderate" ~ 2,
      FrostVulnerability == "Low" ~ 1,
      TRUE ~ NA_real_  
    ),
    
    ## Heat Vulnerability Weights
    HeatVulnerabilityWeight = case_when(
      HeatVulnerability == "Critical" ~ 5,
      HeatVulnerability == "High" ~ 3,
      HeatVulnerability == "Moderate" ~ 2,
      HeatVulnerability == "Low" ~ 1,
      TRUE ~ NA_real_
    )
  )

## Set as a named vector for direct lookup
frost_weights <- setNames(vulnerability_weights$FrostVulnerabilityWeight, vulnerability_weights$CropTypes)
heat_weights <- setNames(vulnerability_weights$HeatVulnerabilityWeight, vulnerability_weights$CropTypes)

############################
### Risk Index Calculation
############################
finalResults <- finalResults %>%
  mutate(
    
    ## Count Modification Weight
    CountWeight = case_when(
      Count < 500 ~ 0.2,
      Count >= 500 & Count < 1000 ~ 0.4,
      Count >= 1000 & Count < 5000 ~ 0.6,
      Count >= 5000 & Count < 10000 ~ 0.8,
      Count >= 10000 & Count < 50000 ~ 1.0,
      Count >= 50000 & Count < 100000 ~ 1.2,
      Count >= 100000 & Count < 500000 ~ 1.4,
      Count >= 500000 ~ 1.6
    ),
    
    
    ## Ensure all necessary variables are numeric and NAs are handled
    FrostVulnerabilityWeight = as.numeric(frost_weights[Crop]),
    HeatVulnerabilityWeight = as.numeric(heat_weights[Crop]),
    TotalDeviationColdOpt = as.numeric(TotalDeviationColdOpt),
    TotalDeviationHeatOpt = as.numeric(TotalDeviationHeatOpt),
    TotalDeviationColdAbs = as.numeric(TotalDeviationColdAbs),
    TotalDeviationHeatAbs = as.numeric(TotalDeviationHeatAbs),
    TotalNormDeviation = as.numeric(TotalNormDeviation),
    
    ## Calculate the weighted deviations
    WeightedColdOptDeviation = TotalDeviationColdOpt * FrostVulnerabilityWeight,
    WeightedHeatOptDeviation = TotalDeviationHeatOpt * HeatVulnerabilityWeight,
    WeightedColdAbsDeviation = TotalDeviationColdAbs * FrostVulnerabilityWeight * TotalNormDeviation,
    WeightedHeatAbsDeviation = TotalDeviationHeatAbs * HeatVulnerabilityWeight * TotalNormDeviation,

    ## Scale each weighted deviation by the logarithm of the count to normalize large values
    ScaledColdOptDeviation = WeightedColdOptDeviation * log1p(Count)^2 * CountWeight,
    ScaledHeatOptDeviation = WeightedHeatOptDeviation * log1p(Count)^2 * CountWeight,
    ScaledColdAbsDeviation = WeightedColdAbsDeviation * log1p(Count)^2 * CountWeight,
    ScaledHeatAbsDeviation = WeightedHeatAbsDeviation * log1p(Count)^2 * CountWeight,

    ## Sum scaled deviations to form the total risk index
    TotalRiskIndex = ScaledColdOptDeviation + ScaledHeatOptDeviation +
                     ScaledColdAbsDeviation + ScaledHeatAbsDeviation
  )

# Output to check results
print(finalResults)

myOranges <- finalResults %>% 
  filter(Crop == 'Oranges')# %>% 
 # filter(DailyCounty == 'Fresno')



```


```{r indexVis}

## Check the data types and look at the content of DailyLat and DailyLong
str(finalResults$DailyLat)
str(finalResults$DailyLong)

## If they are not numeric, convert them
finalResults$DailyLat <- as.numeric(as.character(finalResults$DailyLat))
finalResults$DailyLong <- as.numeric(as.character(finalResults$DailyLong))

## Handle potential NA values that arise from conversion errors
finalResults <- finalResults %>%
  filter(!is.na(DailyLat) & !is.na(DailyLong))

## Convert Year and Month to numeric if they are not already
finalResults$Year <- as.numeric(as.character(finalResults$Year))
finalResults$Month <- as.numeric(as.character(finalResults$Month))


## Scaling ########
finalResults$NormalizedRiskIndex <- scales::rescale(finalResults$TotalRiskIndex, to = c(0, 100))

finalResults$LogRiskIndex <- log1p(finalResults$TotalRiskIndex)  # log1p ensures log(1 + x) to handle zero values smoothly

finalResults$QuantileRiskIndex <- ecdf(finalResults$TotalRiskIndex)(finalResults$TotalRiskIndex) * 100  # Converts to percentile ranking



## Create a color palette that adjusts based on data
getRiskColor <- function(risk) {
  cut(risk,
      breaks = quantile(risk, probs = seq(0, 1, by = 0.25), na.rm = TRUE),
      labels = c("green", "yellow", "orange", "red"),
      include.lowest = TRUE)
}
finalResults$RiskColor <- getRiskColor(finalResults$TotalRiskIndex)
############

ui <- fluidPage(
  theme = shinytheme("flatly"),
  titlePanel("Crop Risk Visualization"),
  sidebarLayout(
    sidebarPanel(
      selectInput("selectedCrop", "Choose a Crop:", choices = unique(finalResults$Crop)),
      sliderInput("selectedYear", "Year:", 
                  min = min(finalResults$Year, na.rm = TRUE), 
                  max = max(finalResults$Year, na.rm = TRUE), 
                  value = range(finalResults$Year, na.rm = TRUE)),
      sliderInput("selectedMonth", "Month:", 
                  min = 1, max = 12, value = 1),
      selectInput("scalingMethod", "Select Scaling Method:", 
                  choices = c("Linear", "Logarithmic", "Quantile")),
      tags$hr(),
      tags$p("Adjust the filters to change the maps dynamically. The risk levels are visualized by color intensity, with more severe risks shown in darker shades.")
    ),
    mainPanel(
      h4("Risk Index Map"),
      leafletOutput("riskMap")
    )
  )
)

server <- function(input, output) {
  # Reactive expression to handle scaling based on selected method
  scaledRiskIndex <- reactive({
    data <- finalResults
    if (input$scalingMethod == "Linear") {
      data$ScaledRiskIndex <- scales::rescale(data$TotalRiskIndex, to = c(0, 100))
    } else if (input$scalingMethod == "Logarithmic") {
      data$ScaledRiskIndex <- log1p(data$TotalRiskIndex)
    } else if (input$scalingMethod == "Quantile") {
      data$ScaledRiskIndex <- ecdf(data$TotalRiskIndex)(data$TotalRiskIndex) * 100
    }
    data
  })
  
  output$riskMap <- renderLeaflet({
    # Filter data based on user input
    filteredData <- scaledRiskIndex() %>%
      filter(Crop == input$selectedCrop, Year == input$selectedYear, Month == input$selectedMonth)

    # Create a color palette based on scaled risk index
    colorPalette <- colorNumeric(palette = c("green", "yellow", "orange", "red"), domain = filteredData$ScaledRiskIndex)

    leaflet(filteredData) %>%
      addTiles() %>%
      addCircleMarkers(
        lng = ~DailyLong, lat = ~DailyLat,
        color = ~colorPalette(ScaledRiskIndex),
        popup = ~paste("County: ", DailyCounty,
                       "<br>Total Deviation Cold Optimal: ", TotalDeviationColdOpt,
                       "<br>Total Deviation Cold Absolute: ", TotalDeviationColdAbs,
                       "<br>Total Deviation Heat Optimal: ", TotalDeviationHeatOpt,
                       "<br>Total Deviation Heat Absolute: ", TotalDeviationHeatAbs),
        opacity = 1, fillOpacity = 0.8,
        radius = ~ifelse(ScaledRiskIndex < 25, 5, ifelse(ScaledRiskIndex < 50, 10, 15))
      ) %>%
      addLegend("bottomright", pal = colorPalette, values = ~ScaledRiskIndex, title = "Risk Index", opacity = 0.5)
  })
}

# Run the app
shinyApp(ui = ui, server = server)
```   






